### PR TITLE
Remove google doc

### PR DESCRIPTION
**Pull request by h4ck3rm1k3**
move the google doc to markdown.

### CODE REVIEW

**Comment by Alan-R** [comment]
Thanks for doing this.

I've attached a copy of the contributor agreement - mainly stating that
this is your work. I'm good with it being based on mine.  Please provide
me a signed copy.  The web site describes how here:
    http://itbestpractices.info/contributor-agreements/

Just so ya know...
I'm going to keep this web site, so, don't bother converting the web
site to markdown ;-)

It's not going to have a big role, but a non-Github web site with its
own domain is a good thing.

On 07/09/2015 07:33 PM, James Michael DuPont wrote:

> move the google doc to markdown.
> 
> ---
> 
> ```
>     You can view, comment on, or merge this pull request online at:
> ```
> 
>   https://github.com/IT-bestpractices/root/pull/2
> 
> ```
>     Commit Summary
> ```
> - Create Proposal.md
> - Update README.md
>   
>   ```
>   File Changes
>   ```
> - _A_ Proposal.md
>   https://github.com/IT-bestpractices/root/pull/2/files#diff-0 (74)
> - _M_ README.md
>   https://github.com/IT-bestpractices/root/pull/2/files#diff-1 (4)
>   
>   ```
>   Patch Links:
>   ```
> - https://github.com/IT-bestpractices/root/pull/2.patch
> - https://github.com/IT-bestpractices/root/pull/2.diff
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/IT-bestpractices/root/pull/2.

## 

Alan Robertson / CTO
AlanR@AssimilationSystems.com mailto:AlanR@AssimilationSystems.com/ +1
303.947.7999

Assimilation Systems Limited
http://AssimilationSystems.com

Twitter https://twitter.com/ossalanr Linkedin
https://www.linkedin.com/in/alanr skype
https://htmlsig.com/skype?username=alanr_unix.sh

**Comment by h4ck3rm1k3** [comment]
a link to the contrib agreement would be good. If you want to setup a git hub hosted/based markdown website i can help with that.

**Comment by h4ck3rm1k3** [comment]
Oh I found the attachment. thanks.

**Comment by Alan-R** [comment]
I'm planning on putting it up on GitHub, but CCed you personally and
included it as an attachment as an expedient measure that was going to
let me get to bed on time ;-). I'll put it up today.

On 07/09/2015 09:25 PM, James Michael DuPont wrote:

> Oh I found the attachment. thanks.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/IT-bestpractices/root/pull/2#issuecomment-120212495.

## 

Alan Robertson / CTO
AlanR@AssimilationSystems.com mailto:AlanR@AssimilationSystems.com/ +1
303.947.7999

Assimilation Systems Limited
http://AssimilationSystems.com

Twitter https://twitter.com/ossalanr Linkedin
https://www.linkedin.com/in/alanr skype
https://htmlsig.com/skype?username=alanr_unix.sh

**Comment by h4ck3rm1k3** [comment]
Dear Alan,
I was not able to find the gpg key for info@itbestpractices.com, so I used the
Key that I found of your on keybase. 
I have read and agree to the terms of the attached document for contributions to the IT Best Practices Project.

Submitting this digitally signed email to Assimilation Systems Limited constitutes my acceptance of the terms of the attached agreement and I provide this email as a legally binding signature to the unmodified agreement attached to this signed email.

James Michael DuPont
jamesmichaeldupont@googlemail.com
Friday July 11, 2015

-----BEGIN PGP MESSAGE-----
Version: GnuPG v1

owFtkl9IVEEUxnf9Vy5YIT6J2kgZKLqoWfRP0jBJ10DRQEqCuXdn74577531zlxj
W9ZEoajUFAqiF5/KNFjLF7WEsKzAUomkLJLKTC3L9iXFymzuykZBbzOH73zf78yZ
1phwU5h5rGRb5xbf1THz44+C6Uj7QGEBghrIl6GabikCJyAFKmEACjICjAAHVu2A
ORGQ3BJwIQ9wEA1g1UHyMBMQZW4NigyLiFpFoqQDSkAR0CkK9lhsXM+ckPGag+jc
iDiAh+gaIKrhJUCKrICHOmEtAhqCdgC5CEoaCmYbsQxpCjX6jAtkDIpObm4noq4g
lQVpRKIyDQs6w0Slob6iCnCA44HSEB8/kWokMqvFUq4LCmYMqxKXYgrsWMIMyrIH
UCyp3B4pEMuGUz6lWMEyNKxBuYcyxGFKeIlxFc+lDDOdcXPFA6AoIjeDqohCuP9n
D44XhDeGLQJujdRiO1pDWUvmO4BARlKQSeAbMFANNsh07c/T6KpC7NiB//UMxQRF
3PHvkfjsxVDhuIex6IRI3g8K9FL+epZqo6qsFe26m5fyJEIkea2Lb9ZSqGE79IBi
nRNlZaWD7MysHZaz5oQIkznMFBUZZnwkkyV6U+h3dYjrVr1hKy7/vHv+XtPyQnPb
Mev7nlMjx6P6Fk2X2qdbHxbnPa8WYnNMubbFLr//gS3vXUN3B71SkxL4Ej9V4t2X
cz+2efhOpi3eJ/yIW1qqz+hzBJJcr1vmZhbxTeqL7SmYuJjRcG5oSq38+aF8oXJP
Qtmrmt1vEibJ+Oavv0pi5w/R5e39/qP+3vrE/PM7X9TUfZ7JiW57lNY4OZJ8TfVH
1DW93Di9YbY4cW9q0ugqHa1bSeq//als0HZm4lbX1q4LyW0xT3qsKePOufbhuJmD
b7Pv7qrqvJE75AgP7z4dSGhscKVdXj9YVfN9APi+Xc/yNqd6nkU+bak46Z3tDXhd
ovk3
=bEKQ
-----END PGP MESSAGE-----

my key : https://keybase.io/h4ck3rm1k3/key.asc

**Comment by Alan-R** [comment]
Hi,

I hadn't thought about it before, but I should store the signed
documents on github too... Or at least I think I should...

In any case, it sounds like the web page isn't sufficiently clear. You
must _not_ encrypt the result, and it must be digitally _signed_ with
the key of the person signing it. I'll clarify that.

On 07/10/2015 06:26 AM, James Michael DuPont wrote:

> Dear Alan,
> I was not able to find the gpg key for info@itbestpractices.com
> mailto:info@itbestpractices.com, so I used the
> Key that I found of your on keybase.
> I have read and agree to the terms of the attached document for
> contributions to the IT Best Practices Project.
> 
> Submitting this digitally signed email to Assimilation Systems Limited
> constitutes my acceptance of the terms of the attached agreement and I
> provide this email as a legally binding signature to the unmodified
> agreement attached to this signed email.
> 
> James Michael DuPont
> jamesmichaeldupont@googlemail.com
> mailto:jamesmichaeldupont@googlemail.com
> Friday July 11, 2015
> 
> Dear Alan,
> I was not able to find the gpg key for info@itbestpractices.com, so I
> used the
> Key that I found of your on keybase.
> I have read and agree to the terms of the attached document for
> contributions to the IT Best Practices Project.
> 
> Submitting this digitally signed email to Assimilation Systems Limited
> constitutes my acceptance of the terms of the attached agreement and I
> provide this email as a legally binding signature to the unmodified
> agreement attached to this signed email.
> 
> James Michael DuPont
> jamesmichaeldupont@googlemail.com
> Friday July 11, 2015
> 
> my key : https://keybase.io/h4ck3rm1k3/key.asc
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/IT-bestpractices/root/pull/2#issuecomment-120398860.

## 

Alan Robertson / CTO
AlanR@AssimilationSystems.com mailto:AlanR@AssimilationSystems.com/ +1
303.947.7999

Assimilation Systems Limited
http://AssimilationSystems.com

Twitter https://twitter.com/ossalanr Linkedin
https://www.linkedin.com/in/alanr skype
https://htmlsig.com/skype?username=alanr_unix.sh

**Comment by h4ck3rm1k3** [comment]
I have updated my comment to sign the message like this 

```
cat agreement.txt | gpg -r 717A640E -r 4DAB7996 --sign --armor > message.txt
```

**Comment by h4ck3rm1k3** [comment]
Here a better one :

```
cat agreement.txt | gpg -r 717A640E -r 4DAB7996 --clearsign  --sign --armor > message.txt
```

-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

Dear Alan,
I was not able to find the gpg key for info@itbestpractices.com, so I used the
Key that I found of your on keybase. 
I have read and agree to the terms of the attached document for contributions to the IT Best Practices Project.

Submitting this digitally signed email to Assimilation Systems Limited constitutes my acceptance of the terms of the attached agreement and I provide this email as a legally binding signature to the unmodified agreement attached to this signed email.

James Michael DuPont
jamesmichaeldupont@googlemail.com
Friday July 11, 2015
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1

iQEcBAEBAgAGBQJVn7zPAAoJEM9MJqkjfaXPfgwIAJEwbDaZod7J7s/NAoiI2Lfr
eEVCr85VDrmX+JPEqQhWPviFR368AWNtICAeaX6TpzBVsUZPj+wqhCRNGKVFXqfH
74rUXm42dd6zyAtIOn623ZK7KLbFNcxl2C8868aVv+Drn0dXlLplArGNPYQ66B+P
kvacvdO/ACn+/z5wjNZ43UWxHBrH9/ggZITLft4fD48cR11yZlMvvHtTO8+8ihPO
MktmIRbSu8v5PKWEMiQeiX9g5fcMz5UizmYR4sYF4YKaeqVJK9JCLBMnWosgL3ZE
a7kiazdQOtzep3hW+zxWcGEiObXVeXp8iou+gK2k8belJHPpwf9wZBiW0lP5P5Y=
=X+Tr
-----END PGP SIGNATURE-----

**Pull request merged**
